### ISSUE TITLE
Album application returns a blank screen for each action

### ISSUE THREAD

**Issue by Farsideman** [zendframework/ZendSkeletonApplication#308] opened 2015-09-15 01:13 UTC
Hello,

I am new to this framework and could really use some help.

When Composer updated the framework to 2.5 my Album application failed to return a view of the updated list of Albums using the Add, Edit, and Delete actions. 

Thanks

**Comment by Maks3w** [comment] 2015-09-15 06:43
Seems you have a PHP error in some part of your code. Check the error logs of your web server.

**Comment by Farsideman** [comment] 2015-09-20 03:06
The web server logs did not record any errors.

**Comment by Gildus** [comment] 2015-09-20 13:56
The configuration for php.ini change for show all errors and the option "error_reporting" like E_ALL then tell us about the errors in your web server.

**Comment by Farsideman** [comment] 2015-09-22 05:03
php.ini changed to E_ALL. Album actions tested. No errors reported.

**Comment by Farsideman** [comment] 2015-09-22 05:42
I also tried ini_set('display_errors', 1); right after the opening php tag in Album index.php. Nothing reported. I then tried die('test'); and index.php was called and "test" is displayed but album data is not passed.

**Comment by Farsideman** [comment] 2015-09-29 03:26
Hi again,

I reinstalled the Skeleton Application and then followed the Album tutorial religiously today. There are no errors in the code. When I go to add an album the database is updated, the route remains as http://../Album/add, and a empty page is displayed. 

There are no errors reported in any of the server logs.

I someone looking into this problem?

**Comment by Farsideman** [comment] 2015-10-01 03:18
MAMP server running PHP 5.6.7.
Skeleton Application has "php": ">=5.5" and "zendframework/zendframework": "~2.5" required by Composer.

**Comment by F17** [comment] 2016-02-03 17:53
i have similar problem. I do http://framework.zend.com/manual/current/en/in-depth-guide/first-module.html and i don't have erros if i reload the page something like "The requested controller could not be mapped to an existing controller class." 
I set:
      error_reporting(E_ALL);
     ini_set("display_errors", 1);

**Comment by weierophinney** [comment] 2016-06-09 20:02
Tutorial questions should be raised against the documentation, not the skeleton application.

Coincidentally, I'm updating the album tutorial for the zend-mvc v3 version of the skeleton application, and ran with the original before starting the updates, and had no issues. The issue is very likely related to PHP configuration and/or missing dependencies.

Either way, closing. Feel free to try the updated version at https://zendframework.github.io/tutorials/ and report issues against that repository if you continue to have issues.

**Closed by weierophinney** 2016-06-09 20:02 UTC
