### ISSUE TITLE
fatal error: pcre.h: No such file or directory

### ISSUE THREAD

**Issue by 2pd** [zendframework/ZendSkeletonApplication#414] opened 2017-05-12 12:55 UTC
I got this error when build the app by docker. Installing libpcre3-dev will fix the issue.
`&& apt-get install -y git zlib1g-dev libpcre3-dev \`

**Comment by weierophinney** [comment] 2017-10-31 14:36
Perhaps you have an outdated php:7.0-apache container? The latest has `libpcre3-dev` as an explicit dependency (see https://github.com/docker-library/php/blob/89894ff2da4da406d52931f1acebf9a2f349a898/7.0/jessie/apache/Dockerfile#L17), and when I ran a shell in the container, `apt list --installed` shows both that package and `zlib1g-dev` as installed.

Closing, as I cannot reproduce, and the official php containers install the dependencies requested.

**Closed by weierophinney** 2017-10-31 14:36 UTC

**Comment by webimpress** [comment] 2017-10-31 14:39
@2pd you can try update your container by running:
```console
$ docker pull php:7.0-apache
```
